# Generated by Django 5.2.4 on 2025-08-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='uniq_profile_opportunity_application',
        ),
        migrations.RemoveConstraint(
            model_name='applicationanswer',
            name='uniq_application_question_answer',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_organis_ab063b_idx',
            old_name='applications_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='application_opportu_56305f_idx',
            old_name='applications_opp_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('profile', 'opportunity')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationanswer',
            unique_together={('application', 'question')},
        ),
    ]
