# Generated by Django 5.2.4 on 2025-08-04 11:26

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
